---
title: "PA1_template.md"
author: "Kyaw Thu"
date: "Friday, April 10, 2015"
output: html_document
---
echo = TRUE  # Always make code visible



#**Loading and preprocessing the data**#

Before processing reading data file, ckeck column names and date setting with lattice will be made.

library(ggplot2)
activity <- read.csv("activity.csv", colClasses = c("numeric", "character", "numeric"))
names(activity)

activity$date = as.Date(activity$date, format="%Y-%m-%d")


#**What is mean total number of steps taken per day**#


*Total number of steps taken per day and ignore NA value*


TotalStepsPD= aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)



*Histogram of the total number of steps taken each day*
qplot(steps, data = TotalStepsPD) +
 geom_histogram(colour="black", fill="green")+
 labs(size= "Nitrogen",
       x = "Steps",
       y = "Days",
       title = "Histogram of Total Number of Steps taken by day")


options(scipen = 50, digits = 5)


Mean and median total number of steps taken per day

*Report of Mean and median of total number of steps*

It was found that average total number of steps per day is 10766 and median value is 10765.

.Average daily steps will be produced by mean function.
v1<-mean(TotalStepsPD$steps)
v1
.Middle value of steps in the activity data is the median.
m1<-median(TotalStepsPD$steps)
m1

#**What is the average daily activity pattern?**#


Average daily activity pattern can be analysed by timeseries function and produced its plot.

DailyPattern <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)

plot(row.names(DailyPattern), DailyPattern, type = "l", xlab = "5-min interval", 
    ylab = "Average across all Days", main = "Time Series Analysis\n Average daily activity pattern", col = "blue")

*Maximum daily steps*
5-minute interval, on average across all the days in the dataset, contains the maximum number of steps 835.

max_interval <- which.max(DailyPattern)
names(max_interval)

#**Imputing missing values**#

*Report of the total number of missing values in the dataset*

*2304 NA values included in activity dataset.*

na_Total <- sum(is.na(activity))
na_Total


*Filling in all of the missing values in the dataset*

AverageSteps <- aggregate(steps ~ interval, data = activity, FUN = mean)
naAdd <- numeric()
for (i in 1:nrow(activity)) {
    obs <- activity[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(AverageSteps, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    naAdd <- c(naAdd, steps)
}

*Create a new dataset that is equal to the original dataset but with the missing data filled in.*

NewStepsPD <- activity
NewStepsPD$steps <- naAdd

*New Dataset include fill NA values*
NewTotalStepsPD <- aggregate(steps ~ date, data = NewStepsPD, sum, na.rm = TRUE)

# Show as histogram

qplot(steps, data = NewTotalStepsPD) +
 geom_histogram(colour="black", fill="Orange")+
 labs(size= "Nitrogen",
       x = "Steps",
       y = "Days",
       title = "Histogram of New Total Number of Steps taken by day")





*Report on mean and median of steps taken each day*

It was found that both mean and mean are the same value of 10766 steps. 

v2<-mean(NewTotalStepsPD$steps)
m2<-median(NewTotalStepsPD$steps)
v2
m2

*Value diffenences of mean and median from without NA*
MeanDiff=v2-v1
MedianDiff=m2-m1

MeanDiff
MedianDiff

*Differences*

It was discovered that there is only negligable difference in the mean and median values from imputing missing NA values from the dataset.

The difference can be visualized in the following graph:
 
TotalStepsPD$type <- as.factor("Original")
NewTotalStepsPD$type <- as.factor("Imputed")
DiffForm <- rbind(TotalStepsPD, NewTotalStepsPD)
# Plot histogram
ggplot(DiffForm, aes(steps, fill = type))+
theme(legend.title= element_blank())+
geom_bar(position= "dodge", binwidth= 400)+
labs(title="Comparision of Two Datasets", x="Number of Steps", y="Number of Days")

#**Are there differences in activity patterns between weekdays and weekebds?**#


*Create a new factor variable in the dataset with two levels - "weekday" and "weekend"*

days <- weekdays(activity$date)
daylevel <- vector()
for (i in 1:nrow(activity)) {
    if (days[i] == "Saturday") {
        daylevel[i] <- "Weekend"
    } else if (days[i] == "Sunday") {
        daylevel[i] <- "Weekend"
    } else {
        daylevel[i] <- "Weekday"
    }
}

activity$daylevel <- daylevel
activity$daylevel <- factor(activity$daylevel)

*The difference between weekend and weekdays values can be visualized in the following graph:*

library(lattice)

AvgSteps <- aggregate(steps ~ interval + daylevel, data = activity, mean)
names(AvgSteps) <- c("interval", "daylevel", "steps")
xyplot(steps ~ interval | daylevel, AvgSteps, type = "l", layout = c(1, 2), 
    xlab = "Interval", ylab = "Number of steps")
    
    
    
    
